"""Extended values for column string in game.

Revision ID: c074e57e9986
Revises: 0844618c5961
Create Date: 2025-03-25 08:18:50.569738

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c074e57e9986'
down_revision: str | None = '0844618c5961'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'rating',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('game', 'price_final',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=100, scale=2),
               existing_nullable=True)
    op.alter_column('game', 'short_description',
               existing_type=sa.VARCHAR(length=1500),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.alter_column('game', 'short_description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=1500),
               existing_nullable=True)
    op.alter_column('game', 'price_final',
               existing_type=sa.Numeric(precision=100, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('game', 'rating',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
