"""removed hashed from user password.

Revision ID: 95c9783622ba
Revises: 9631f7ce28e1
Create Date: 2025-03-10 21:27:25.920257

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '95c9783622ba'
down_revision: str | None = '9631f7ce28e1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_game_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'game', ['game_id'], ['id_game'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    op.add_column('user', sa.Column('password', sa.String(length=250), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('user', 'password')
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.create_foreign_key('question_game_id_fkey', 'question', 'game', ['game_id'], ['id_game'])
    # ### end Alembic commands ###
