"""Edited question.

Revision ID: 0844618c5961
Revises: 22ea05f943bb
Create Date: 2025-03-25 07:51:57.198843

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0844618c5961'
down_revision: str | None = '22ea05f943bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_game_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    op.drop_column('question', 'game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.create_foreign_key('question_game_id_fkey', 'question', 'game', ['game_id'], ['id_game'])
    # ### end Alembic commands ###
