"""Added models for game, question, survey.

Revision ID: 9631f7ce28e1
Revises: ef8beff37aa3
Create Date: 2025-03-10 21:12:58.355676

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9631f7ce28e1'
down_revision: str | None = 'ef8beff37aa3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('gamename', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_game'),
    schema='public'
    )
    op.create_index(op.f('ix_public_game_gamename'), 'game', ['gamename'], unique=False, schema='public')
    op.create_table('survey',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('survey_id'),
    schema='public'
    )
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['public.game.id_game'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['public.survey.survey_id'], ),
    sa.PrimaryKeyConstraint('question_id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question', schema='public')
    op.drop_table('survey', schema='public')
    op.drop_index(op.f('ix_public_game_gamename'), table_name='game', schema='public')
    op.drop_table('game', schema='public')
    # ### end Alembic commands ###
