"""Edited game model.

Revision ID: 22ea05f943bb
Revises: d10cc0c3ed86
Create Date: 2025-03-24 21:22:01.912093

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '22ea05f943bb'
down_revision: str | None = 'd10cc0c3ed86'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('game', sa.Column('header_image', sa.String(length=512), nullable=True))
    op.add_column('game', sa.Column('date_release', sa.Date(), nullable=True))
    op.add_column('game', sa.Column('win', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('mac', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('linux', sa.Boolean(), nullable=True))
    op.add_column('game', sa.Column('rating', sa.String(length=20), nullable=True))
    op.add_column('game', sa.Column('positive_ratio', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('user_reviews', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('price_final', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('game', sa.Column('short_description', sa.String(length=1500), nullable=True))
    op.drop_index('ix_public_game_gamename', table_name='game')
    op.drop_index('ix_public_game_steam_link', table_name='game')
    op.drop_column('game', 'steam_link')
    op.drop_column('game', 'gamename')
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint('question_game_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'game', ['game_id'], ['id_game'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_game_id_fkey', 'question', 'game', ['game_id'], ['id_game'])
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.add_column('game', sa.Column('gamename', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('game', sa.Column('steam_link', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_index('ix_public_game_steam_link', 'game', ['steam_link'], unique=False)
    op.create_index('ix_public_game_gamename', 'game', ['gamename'], unique=False)
    op.drop_column('game', 'short_description')
    op.drop_column('game', 'price_final')
    op.drop_column('game', 'user_reviews')
    op.drop_column('game', 'positive_ratio')
    op.drop_column('game', 'rating')
    op.drop_column('game', 'linux')
    op.drop_column('game', 'mac')
    op.drop_column('game', 'win')
    op.drop_column('game', 'date_release')
    op.drop_column('game', 'header_image')
    op.drop_column('game', 'title')
    # ### end Alembic commands ###
