"""Extended title.

Revision ID: 73919ff7e447
Revises: ee1c305d6569
Create Date: 2025-03-25 08:28:40.328603

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '73919ff7e447'
down_revision: str | None = 'ee1c305d6569'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('game', 'header_image',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.alter_column('game', 'header_image',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('game', 'title',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
