"""added user table.

Revision ID: ef8beff37aa3
Revises: 
Create Date: 2025-03-09 12:02:49.794448

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ef8beff37aa3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_username'), 'user', ['username'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_username'), table_name='user', schema='public')
    op.drop_table('user', schema='public')
    # ### end Alembic commands ###
