"""Added reaction.

Revision ID: 411aaee83cc1
Revises: 73919ff7e447
Create Date: 2025-03-25 09:13:09.122678

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '411aaee83cc1'
down_revision: str | None = '73919ff7e447'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction',
    sa.Column('reaction_id', sa.Integer(), nullable=False),
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('has_played', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('want_to_play', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_game'], ['public.game.id_game'], ),
    sa.ForeignKeyConstraint(['id_user'], ['public.user.id_user'], ),
    sa.PrimaryKeyConstraint('reaction_id'),
    schema='public'
    )
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.drop_table('reaction', schema='public')
    # ### end Alembic commands ###
