"""Extended more.

Revision ID: 4ad02da9efd9
Revises: c074e57e9986
Create Date: 2025-03-25 08:25:48.830701

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4ad02da9efd9'
down_revision: str | None = 'c074e57e9986'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'price_final',
               existing_type=sa.NUMERIC(precision=100, scale=2),
               type_=sa.Numeric(precision=1000, scale=2),
               existing_nullable=True)
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.alter_column('game', 'price_final',
               existing_type=sa.Numeric(precision=1000, scale=2),
               type_=sa.NUMERIC(precision=100, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
