"""Added link to game.

Revision ID: 03db7f9fc5ae
Revises: dd7ca184458d
Create Date: 2025-03-10 21:36:31.811700

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '03db7f9fc5ae'
down_revision: str | None = 'dd7ca184458d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('steam_link', sa.String(length=512), nullable=False))
    op.create_index(op.f('ix_public_game_steam_link'), 'game', ['steam_link'], unique=False, schema='public')
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint('question_game_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'question', 'game', ['game_id'], ['id_game'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_game_id_fkey', 'question', 'game', ['game_id'], ['id_game'])
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.drop_index(op.f('ix_public_game_steam_link'), table_name='game', schema='public')
    op.drop_column('game', 'steam_link')
    # ### end Alembic commands ###
