"""unique username.

Revision ID: d10cc0c3ed86
Revises: 2b62c1324b56
Create Date: 2025-03-22 14:47:48.163804

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd10cc0c3ed86'
down_revision: str | None = '2b62c1324b56'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_game_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'game', ['game_id'], ['id_game'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    op.drop_index('ix_public_user_username', table_name='user')
    op.execute('truncate public.user restart identity')
    op.create_index(op.f('ix_public_user_username'), 'user', ['username'], unique=True, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_username'), table_name='user', schema='public')
    op.create_index('ix_public_user_username', 'user', ['username'], unique=False)
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.create_foreign_key('question_game_id_fkey', 'question', 'game', ['game_id'], ['id_game'])
    # ### end Alembic commands ###
