"""Added name to survey.

Revision ID: 2b62c1324b56
Revises: 0b3e105e3a16
Create Date: 2025-03-11 07:49:21.108538

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2b62c1324b56'
down_revision: str | None = '0b3e105e3a16'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_game_id_fkey', 'question', type_='foreignkey')
    op.drop_constraint('question_survey_id_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'survey', ['survey_id'], ['survey_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'question', 'game', ['game_id'], ['id_game'], source_schema='public', referent_schema='public')
    op.add_column('survey', sa.Column('survey_name', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_public_survey_survey_name'), 'survey', ['survey_name'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_survey_survey_name'), table_name='survey', schema='public')
    op.drop_column('survey', 'survey_name')
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'question', schema='public', type_='foreignkey')
    op.create_foreign_key('question_survey_id_fkey', 'question', 'survey', ['survey_id'], ['survey_id'])
    op.create_foreign_key('question_game_id_fkey', 'question', 'game', ['game_id'], ['id_game'])
    # ### end Alembic commands ###
